custom tag

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -41,10 +41,32 @@ jobs:
       run: echo "TAG_DOES_NOT_EXIST=$(git tag | grep -q ${{ env.CUSTOM_TAG }} ; echo $?)" >> $GITHUB_ENV
     - name: test commit
       run: git rev-parse HEAD
-    - name: Bump version and push tag
-      uses: anothrNick/github-tag-action@1.34.0
+    - name: push tag
       if: env.TAG_DOES_NOT_EXIST=='1'
-      env:
-        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
-        CUSTOM_TAG: ${{ env.CUSTOM_TAG }}
-        RELEASE_BRANCHES: '.*'
+      run:
+        git_refs_response=$(
+          curl -X POST -H "Accept: application/vnd.github.v3+json" \
+          https://api.github.com/repos/realoptions/demo-api-app-flutter/git/refs \
+          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
+          -d '{
+            "ref": "refs/tags/${{ env.CUSTOM_TAG }}",
+            "sha": "$(git rev-parse HEAD)"
+          }'
+        )
+
+        git_ref_posted=$( echo "${git_refs_response}" | jq .ref | tr -d '"' )
+
+        echo "::debug::${git_refs_response}"
+        if [ "${git_ref_posted}" = "refs/tags/${new}" ]; then
+          exit 0
+        else
+          echo "::error::Tag was not created properly."
+          exit 1
+        fi
+    #- name: Bump version and push tag
+    #  uses: anothrNick/github-tag-action@1.34.0
+    #  if: env.TAG_DOES_NOT_EXIST=='1'
+    #  env:
+    #    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+    #    CUSTOM_TAG: ${{ env.CUSTOM_TAG }}
+    #    RELEASE_BRANCHES: '.*'
